# Seed for all RNG
# Set to 0 for no seed
# 1000101
random_seed: 0
# Rounds in a game. Must be even
rounds: 30

economy:
  # T win by elimination
  elimination: 3250
  # CT win by time
  time_win: 3250
  # CT win by defusal
  defusal: 3500
  # T win by detonation
  detonation: 3500

  # T bonus for planting and killing all CTs
  plant_elimination: 300
  # T bonus for planting and losing the round
  plant_loss: 800
  # Bonus given immediately to planter
  planter: 300
  # Bonus given immediately to defuser
  defuser: 300
  # Bonus given to surviving on T
  t_survivor: 0

  # Money given to pistol round losers
  pistol_loss: 1900
  # Incremental loss bonus values
  loss: [1400, 1900, 2400, 2900, 3400]

  starting_money: 800

player:
  pistol:
    t: glock
    ct: [p2000, usps]
  roles:
    # How many players will be designated AWPers (prioritize saving for
    # an AWP)
    awp: 1
    # Chance of a double-AWP setup
    double_awp: 0.05

buy_settings:
  pistol_round:
    # Amount of kits that will always be purchased on pistol rounds
    kits: 1

    # Recursive, weighted priority list for purchases.
    # Purchases are evaluated in order. If an entry is a list,
    # one item is chosen with the given probability.
    # If no probabilities are given, they will be assumed to be equal.
    # Specify weighted probabilities for a list by adding list entries
    # of the form: `{n: <name>, p: <probability>}`
    # If an entry contains a `c` key (c for "choices"), it will be
    # evaluated recursively.
    # If an entry contains a `t` and `ct` key,
    # the recursion will branch based on the player's current side.
    # A player will attempt to buy until the list is exhausted or
    # they run out of money.

    # For example, the default value will first choose between a
    # pistol or kevlar, with kevlar chosen 90% of the time. If pistol
    # is chosen and the player is on T side, then they will randomly
    # choose either the deagle, p250, or tec9. If they are CT, they
    # will choose the deagle, p250, or fiveseven each with 30% chance,
    # or the cz75 with 10% chance.
    # Following this, they will unconditionally attempt to buy a
    # flashbang, and finally try to buy either a smoke or a he grenade.

    # NOTE: Probabilities are relative, and so they need not sum to 1
    #       (See: https://docs.python.org/3/library/random.html#random.choices)
    # NOTE: If you set a probability for one item, you must also set
    #       it for all other entries in that list.
    # NOTE: A priority list must be defined for all roles
    #       use YAML anchors to duplicate entries if desired
    purchase_priorities:
      default: &default
      - [
      {n: kevlar, p: 0.8},
      { n: pistol,
        p: 0.1,
        t: [deagle, p250, tec9],
        ct: [{n: deagle, p: 0.3}, {n: p250, p: 0.3}, {n: fiveseven, p: 0.3}, {n: cz75, p: 0.1}]
      }
      ]
      # This exists to let CTs who bought kits to buy a pistol or grenades
      - {n: pistol, p: 0.4, ct: [p250, []], t: []}
      - flashbang
      - [smoke, he, flashbang]
      rifle: *default
      awp: *default

positioning:
  pistol_round:
    ct:
      a:
        # Percent chance for a given player to be on A site.
        # Otherwise, they will be on B site.
        # Players are shuffled each round so different roles may play
        # different positions.
        # NOTE: The first player in this case has a 100% chance to
        # play A, the second has 90%, etc.
        site_chance: [1, 0.9, 0.7, 0.1, 0]
    t:
      # 50% chance for an A take, else B
      site_chance: 0.5
      # 5% chance for one player to lurk
      lurk: [0.05, 0, 0, 0, 0]

encounter:
  pistol_round:
    # A player with the "lurk" role will add the lurk modifier to their
    # given probability (values >= 1 are guaranteed encounters)
    lurk_modifier: 0.1
    # If a T's encounter chance is rolled, they will choose a
    # random CT to attack
    early: [0.1, 0.1, 0, 0, 0]

weapons:
  special:
    knife:
      price: 0
      award: 1500
      damage: 100
      penetration: 1
  rifle:
    ak47:
      price: 2700
      award: 300
      damage: 36
      penetration: 0.775
      aug:
        price: 3300
        award: 300
        damage: 28
        penetration: 0.9
      famas:
        price: 2050
        award: 300
        damage: 30
        penetration: 0.7
      galil:
        price: 1800
        award: 300
        damage: 30
        penetration: 0.775
      m4a4:
        price: 3100
        award: 300
        damage: 33
        penetration: 0.7
      m4a1s:
        price: 3100
        award: 300
        damage: 33
        penetration: 0.7
      sg553:
        price: 3000
        award: 300
        damage: 30
        penetration: 100
  smg:
    bizon:
      price: 1400
      award: 600
      damage: 27
      penetration: 0.575
    mac10:
      price: 1050
      award: 600
      damage: 29
      penetration: 57.5
    mp7:
      price: 1500
      award: 600
      damage: 29
      penetration: 62.5
    mp5:
      price: 1500
      award: 600
      damage: 27
      penetration: 62.5
    mp9:
      price: 1250
      award: 600
      damage: 26
      penetration: 0.6
    p90:
      price: 2350
      award: 300
      damage: 26
      penetration: 0.69
    ump45:
      price: 1200
      award: 600
      damage: 35
      penetration: 0.65
  pistol:
    deagle:
      price: 700
      award: 300
      damage: 63
      penetration: 0.932
    r8:
      price: 600
      award: 300
      damage: 86
      penetration: 0.932
    berettas:
      price: 400
      award: 300
      damage: 38
      penetration: 0.575
    fiveseven:
      price: 500
      award: 300
      damage: 32
      penetration: 0.9115
    glock:
      price: 200
      award: 300
      damage: 30
      penetration: 0.47
    p2000:
      price: 200
      award: 300
      damage: 35
      penetration: 0.505
    usps:
      price: 200
      award: 300
      damage: 35
      penetration: 0.505
    p250:
      price: 300
      award: 300
      damage: 38
      penetration: 0.64
    cz75:
      price: 500
      award: 100
      damage: 31
      penetration: 0.7765
    tec9:
      price: 500
      award: 300
      damage: 33
      penetration: 0.906
  heavy:
    mag7:
      price: 1300
      award: 900
      damage: 30
      penetration: 0.75
    nova:
      price: 1050
      award: 900
      damage: 26
      penetration: 0.5
    sawedoff:
      price: 1100
      award: 900
      damage: 32
      penetration: 0.75
    xm1014:
      price: 2000
      award: 900
      damage: 20
      penetration: 0.8
    m249:
      price: 5200
      award: 300
      damage: 32
      penetration: 0.8
    negev:
      price: 1700
      award: 300
      damage: 35
      penetration: 0.71
    awp:
      price: 4750
      award: 100
      damage: 115
      penetration: 0.975
    g3sg1:
      price: 5000
      award: 300
      damage: 80
      penetration: 0.825
    scar20:
      price: 5000
      award: 300
      damage: 80
      penetration: 0.825
    ssg08:
      price: 1700
      award: 300
      damage: 88
      penetration: 0.85
equipment:
  grenade:
    he:
      price: 300
      limit: 1
    #      award: 300
    #      damage: 98
    #      penetration: 0.5816
    flashbang:
      price: 200
      limit: 2
    smoke:
      price: 300
      limit: 1
    decoy:
      price: 50
      limit: 1
    molotov:
      price: 400
      limit: 1
    incendiary:
      price: 600
      limit: 1
  gear:
    kevlar:
      price: 650
    helmet:
      # Price if current armor is < 100
      price_damaged: 1000
      price: 350
      limit: 1
    zeus:
      price: 200
      limit: 1
    kit:
      price: 400
      limit: 1